#!/usr/bin/env tsx
/**
 * Test script for YouTube subtitle downloading with Whisper fallback
 * 
 * This script demonstrates:
 * 1. Downloading YouTube subtitles (auto-generated or manual)
 * 2. Falling back to Whisper transcription when subtitles are unavailable
 * 3. Creating overlapping chunks for AI highlight detection
 * 
 * Usage:
 * tsx src/services/test-youtube-subtitle-transcription.ts <youtube-url>
 */

import { TranscriptionService } from './TranscriptionService';
import { YouTubeSubtitleDownloader } from './YouTubeSubtitleDownloader';
import { logger } from '../logger';
import path from 'path';
import fs from 'fs-extra';

async function testYouTubeSubtitleTranscription(url: string) {
  const dataDir = path.join(process.cwd(), 'data', 'test-transcription');
  await fs.ensureDir(dataDir);

  // Initialize services
  const transcriptionService = new TranscriptionService(dataDir);
  const subtitleDownloader = new YouTubeSubtitleDownloader();

  console.log(`\n🎬 Testing YouTube subtitle transcription for: ${url}\n`);

  try {
    // Step 1: Check available subtitles
    console.log('📋 Checking available subtitles...');
    const availableSubtitles = await subtitleDownloader.getAvailableSubtitles(url);
    
    if (availableSubtitles.length > 0) {
      console.log(`Found ${availableSubtitles.length} subtitle tracks:`);
      availableSubtitles.forEach(track => {
        console.log(`  - ${track.language} (${track.languageCode})${track.isAutoGenerated ? ' [Auto-generated]' : ''}`);
      });
    } else {
      console.log('No subtitles available for this video.');
    }

    // Step 2: Transcribe using the improved system
    console.log('\n🎯 Starting transcription (subtitles first, Whisper fallback)...');
    const startTime = Date.now();
    
    const result = await transcriptionService.transcribeYouTubeVideo(url, {
      language: 'en',
      model: 'base',
      preferSubtitles: true
    });

    const duration = (Date.now() - startTime) / 1000;
    
    console.log(`\n✅ Transcription completed in ${duration.toFixed(2)}s`);
    console.log(`Provider: ${result.provider}`);
    console.log(`Model/Source: ${result.modelUsed}`);
    console.log(`Language: ${result.language || result.languageCode}`);
    console.log(`Segments: ${result.segments.length}`);
    console.log(`Word count: ${result.wordCount}`);
    console.log(`Duration: ${result.duration?.toFixed(2)}s`);

    // Step 3: Create overlapping chunks for AI analysis
    console.log('\n🔄 Creating overlapping chunks for highlight detection...');
    const { chunks, metadata } = transcriptionService.createOverlappingChunks(
      result.segments,
      30, // 30 second chunks
      5   // 5 second overlap
    );

    console.log(`Created ${chunks.length} chunks with ${metadata.filter(m => m.overlap).length} overlapping sections`);
    
    // Display first few chunks
    console.log('\nFirst 3 chunks:');
    for (let i = 0; i < Math.min(3, chunks.length); i++) {
      const chunk = chunks[i];
      const meta = metadata[i];
      console.log(`\nChunk ${i + 1} (${meta.startTime.toFixed(1)}s - ${meta.endTime.toFixed(1)}s)${meta.overlap ? ' [Overlapped]' : ''}:`);
      console.log(`Text: ${chunk.slice(0, 2).map(s => s.text).join(' ')}...`);
      console.log(`Segments: ${chunk.length}`);
    }

    // Step 4: Save results
    const outputDir = path.join(dataDir, 'output');
    await fs.ensureDir(outputDir);

    // Save full transcript
    const transcriptPath = path.join(outputDir, 'transcript.json');
    await fs.writeJson(transcriptPath, result, { spaces: 2 });
    console.log(`\n💾 Full transcript saved to: ${transcriptPath}`);

    // Save SRT file
    const srtPath = path.join(outputDir, 'subtitles.srt');
    await transcriptionService.exportTranscription(result, 'srt', srtPath);
    console.log(`💾 SRT file saved to: ${srtPath}`);

    // Save chunks for AI analysis
    const chunksPath = path.join(outputDir, 'chunks.json');
    await fs.writeJson(chunksPath, { chunks, metadata }, { spaces: 2 });
    console.log(`💾 Chunks saved to: ${chunksPath}`);

    // Display sample transcript
    console.log('\n📝 Sample transcript (first 500 characters):');
    console.log(result.text.substring(0, 500) + '...');

  } catch (error) {
    console.error('\n❌ Error:', error);
    logger.error({ error }, 'Test failed');
  }
}

// Run test if called directly
if (require.main === module) {
  const url = process.argv[2];
  
  if (!url) {
    console.error('Usage: tsx test-youtube-subtitle-transcription.ts <youtube-url>');
    console.error('Example: tsx test-youtube-subtitle-transcription.ts https://www.youtube.com/watch?v=dQw4w9WgXcQ');
    process.exit(1);
  }

  testYouTubeSubtitleTranscription(url)
    .then(() => {
      console.log('\n✨ Test completed successfully!');
      process.exit(0);
    })
    .catch((error) => {
      console.error('\n💥 Test failed:', error);
      process.exit(1);
    });
}