import ytdl from 'yt-dlp-exec';
import { logger } from '../logger';
import { TranscriptSegment } from '../types/import';
import * as fs from 'fs';
import * as path from 'path';
import * as os from 'os';

export interface SubtitleTrack {
  language: string;
  languageCode: string;
  isAutoGenerated: boolean;
  format: string;
  url?: string;
}

export interface SubtitleDownloadOptions {
  language?: string; // Preferred language code (e.g., 'en', 'es')
  preferAutoGenerated?: boolean; // Whether to prefer auto-generated subtitles
  format?: 'srt' | 'vtt' | 'json';
}

export interface SubtitleResult {
  success: boolean;
  subtitles?: string; // Raw subtitle content
  segments?: TranscriptSegment[];
  language?: string;
  isAutoGenerated?: boolean;
  error?: string;
}

export class YouTubeSubtitleDownloader {
  /**
   * Get available subtitle tracks for a YouTube video
   */
  public async getAvailableSubtitles(url: string): Promise<SubtitleTrack[]> {
    try {
      logger.info({ url }, 'Fetching available subtitles from YouTube');

      const info = await ytdl(url, {
        dumpSingleJson: true,
        noCheckCertificate: true,
        noWarnings: true,
        quiet: true,
        noPlaylist: true,
        skipDownload: true
      });

      const tracks: SubtitleTrack[] = [];

      // Process both manual and auto-generated subtitles
      if (info.subtitles) {
        for (const [lang, formats] of Object.entries(info.subtitles as Record<string, any[]>)) {
          if (formats && Array.isArray(formats)) {
            for (const format of formats) {
              tracks.push({
                language: this.getLanguageName(lang),
                languageCode: lang,
                isAutoGenerated: false,
                format: format.ext || 'srt',
                url: format.url
              });
            }
          }
        }
      }

      // Process auto-generated subtitles
      if (info.automatic_captions) {
        for (const [lang, formats] of Object.entries(info.automatic_captions as Record<string, any[]>)) {
          if (formats && Array.isArray(formats)) {
            for (const format of formats) {
              tracks.push({
                language: this.getLanguageName(lang),
                languageCode: lang,
                isAutoGenerated: true,
                format: format.ext || 'srt',
                url: format.url
              });
            }
          }
        }
      }

      logger.info({ url, trackCount: tracks.length }, 'Found subtitle tracks');
      return tracks;
    } catch (error) {
      logger.error({ error, url }, 'Failed to fetch available subtitles');
      return [];
    }
  }

  /**
   * Download subtitles from YouTube
   */
  public async downloadSubtitles(
    url: string, 
    options: SubtitleDownloadOptions = {}
  ): Promise<SubtitleResult> {
    try {
      const { language = 'en', preferAutoGenerated = false, format = 'srt' } = options;

      logger.info({ url, language, preferAutoGenerated, format }, 'Downloading YouTube subtitles');

      // First, check available subtitles
      const availableTracks = await this.getAvailableSubtitles(url);
      if (availableTracks.length === 0) {
        return {
          success: false,
          error: 'No subtitles available for this video'
        };
      }

      // Find the best matching track
      let selectedTrack = this.selectBestTrack(availableTracks, language, preferAutoGenerated);
      if (!selectedTrack) {
        // Fallback to any English track
        selectedTrack = availableTracks.find(t => t.languageCode.startsWith('en'));
        if (!selectedTrack) {
          // Fallback to first available track
          selectedTrack = availableTracks[0];
        }
      }

      logger.info({ 
        selectedLanguage: selectedTrack.languageCode, 
        isAutoGenerated: selectedTrack.isAutoGenerated 
      }, 'Selected subtitle track');

      // Create temporary directory for subtitle download
      const tempDir = path.join(os.tmpdir(), 'youtube-subtitles');
      if (!fs.existsSync(tempDir)) {
        fs.mkdirSync(tempDir, { recursive: true });
      }

      // Generate a unique filename for the subtitle
      const tempFilename = `subtitle_${Date.now()}_${Math.random().toString(36).substring(7)}`;
      const outputPath = path.join(tempDir, tempFilename);

      // Download the subtitles
      const ytdlOptions: any = {
        skipDownload: true,
        writeAutoSub: preferAutoGenerated || selectedTrack.isAutoGenerated,
        writeSub: !selectedTrack.isAutoGenerated,
        subLang: selectedTrack.languageCode,
        subFormat: format,
        quiet: true,
        noWarnings: true,
        noCheckCertificate: true,
        paths: tempDir,
        output: `${tempFilename}.%(ext)s`
      };

      logger.info({ ytdlOptions, url }, 'Downloading subtitles with yt-dlp');

      // Execute yt-dlp to download subtitle file
      await ytdl(url, ytdlOptions);
      
      // Parse the subtitle content based on format
      let segments: TranscriptSegment[] = [];
      let subtitleContent = '';

      // Find the downloaded subtitle file
      const subtitleFilePath = path.join(tempDir, `${tempFilename}.${selectedTrack.languageCode}.${format}`);
      
      try {
        if (fs.existsSync(subtitleFilePath)) {
          subtitleContent = fs.readFileSync(subtitleFilePath, 'utf-8');
          segments = this.parseSubtitles(subtitleContent, format);
          
          // Clean up the temporary file
          fs.unlinkSync(subtitleFilePath);
          
          logger.info({ 
            segmentCount: segments.length,
            language: selectedTrack.languageCode 
          }, 'Successfully downloaded and parsed subtitles');
        } else {
          logger.warn({ expectedPath: subtitleFilePath }, 'Subtitle file not found at expected path');
          
          // Try to find any subtitle file that was downloaded
          const files = fs.readdirSync(tempDir);
          const subtitleFile = files.find(f => f.startsWith(tempFilename) && f.endsWith(`.${format}`));
          
          if (subtitleFile) {
            const actualPath = path.join(tempDir, subtitleFile);
            subtitleContent = fs.readFileSync(actualPath, 'utf-8');
            segments = this.parseSubtitles(subtitleContent, format);
            fs.unlinkSync(actualPath);
            
            logger.info({ 
              actualPath,
              segmentCount: segments.length 
            }, 'Found subtitle file at different path');
          }
        }
      } catch (readError) {
        logger.error({ readError, subtitleFilePath }, 'Failed to read subtitle file');
      }

      // If we still don't have subtitles, try downloading them directly
      if (segments.length === 0 && selectedTrack.url) {
        try {
          const response = await fetch(selectedTrack.url);
          subtitleContent = await response.text();
          segments = this.parseSubtitles(subtitleContent, selectedTrack.format as any);
        } catch (fetchError) {
          logger.warn({ fetchError }, 'Failed to fetch subtitles directly from URL');
        }
      }

      if (segments.length > 0) {
        return {
          success: true,
          subtitles: subtitleContent,
          segments,
          language: selectedTrack.languageCode,
          isAutoGenerated: selectedTrack.isAutoGenerated
        };
      } else {
        return {
          success: false,
          error: 'Failed to parse subtitle content'
        };
      }

    } catch (error) {
      logger.error({ error, url }, 'Failed to download subtitles');
      return {
        success: false,
        error: `Failed to download subtitles: ${(error as Error).message}`
      };
    }
  }

  /**
   * Parse subtitle content into segments
   */
  private parseSubtitles(content: string, format: 'srt' | 'vtt' | 'json'): TranscriptSegment[] {
    switch (format) {
      case 'srt':
        return this.parseSRT(content);
      case 'vtt':
        return this.parseVTT(content);
      case 'json':
        return this.parseJSON(content);
      default:
        return this.parseSRT(content); // Default to SRT parsing
    }
  }

  /**
   * Parse SRT format subtitles
   */
  private parseSRT(content: string): TranscriptSegment[] {
    const segments: TranscriptSegment[] = [];
    const blocks = content.trim().split(/\n\s*\n/);

    for (const block of blocks) {
      const lines = block.trim().split('\n');
      if (lines.length >= 3) {
        // Parse timestamp line (e.g., "00:00:01,000 --> 00:00:04,000")
        const timestampMatch = lines[1].match(/(\d{2}):(\d{2}):(\d{2}),(\d{3})\s*-->\s*(\d{2}):(\d{2}):(\d{2}),(\d{3})/);
        
        if (timestampMatch) {
          const startTime = this.parseTimestamp(timestampMatch[1], timestampMatch[2], timestampMatch[3], timestampMatch[4]);
          const endTime = this.parseTimestamp(timestampMatch[5], timestampMatch[6], timestampMatch[7], timestampMatch[8]);
          
          // Join all text lines (skip index and timestamp)
          const text = lines.slice(2).join(' ').replace(/<[^>]*>/g, '').trim();
          
          if (text) {
            segments.push({
              text,
              startTime,
              endTime,
              confidence: 1.0 // Subtitles have perfect confidence
            });
          }
        }
      }
    }

    return segments;
  }

  /**
   * Parse VTT format subtitles
   */
  private parseVTT(content: string): TranscriptSegment[] {
    const segments: TranscriptSegment[] = [];
    const lines = content.split('\n');
    
    let i = 0;
    // Skip header
    while (i < lines.length && !lines[i].includes('-->')) {
      i++;
    }

    while (i < lines.length) {
      const line = lines[i].trim();
      
      // Look for timestamp line
      if (line.includes('-->')) {
        const timestampMatch = line.match(/(\d{2}):(\d{2}):(\d{2})\.(\d{3})\s*-->\s*(\d{2}):(\d{2}):(\d{2})\.(\d{3})/);
        
        if (timestampMatch) {
          const startTime = this.parseTimestamp(timestampMatch[1], timestampMatch[2], timestampMatch[3], timestampMatch[4]);
          const endTime = this.parseTimestamp(timestampMatch[5], timestampMatch[6], timestampMatch[7], timestampMatch[8]);
          
          // Collect text lines
          const textLines: string[] = [];
          i++;
          while (i < lines.length && lines[i].trim() && !lines[i].includes('-->')) {
            textLines.push(lines[i].trim());
            i++;
          }
          
          const text = textLines.join(' ').replace(/<[^>]*>/g, '').trim();
          
          if (text) {
            segments.push({
              text,
              startTime,
              endTime,
              confidence: 1.0
            });
          }
        }
      }
      i++;
    }

    return segments;
  }

  /**
   * Parse JSON format subtitles
   */
  private parseJSON(content: string): TranscriptSegment[] {
    // Check if content is HTML (common error response)
    if (content.trim().startsWith('<!DOCTYPE') || content.trim().startsWith('<html')) {
      logger.warn('Received HTML response instead of JSON subtitles');
      throw new Error('Received HTML response instead of JSON subtitles');
    }

    try {
      const data = JSON.parse(content);
      const segments: TranscriptSegment[] = [];

      // Handle different JSON structures
      if (Array.isArray(data)) {
        for (const item of data) {
          if (item.start !== undefined && item.end !== undefined && item.text) {
            segments.push({
              text: item.text.trim(),
              startTime: parseFloat(item.start),
              endTime: parseFloat(item.end),
              confidence: 1.0
            });
          }
        }
      } else if (data.events && Array.isArray(data.events)) {
        // YouTube's JSON3 format
        for (const event of data.events) {
          if (event.tStartMs !== undefined && event.dDurationMs !== undefined && event.segs) {
            const startTime = event.tStartMs / 1000;
            const endTime = startTime + (event.dDurationMs / 1000);
            const text = event.segs.map((seg: any) => seg.utf8).join('').trim();
            
            if (text) {
              segments.push({
                text,
                startTime,
                endTime,
                confidence: 1.0
              });
            }
          }
        }
      }

      return segments;
    } catch (error) {
      logger.error({ error }, 'Failed to parse JSON subtitles');
      return [];
    }
  }

  /**
   * Parse timestamp components into seconds
   */
  private parseTimestamp(hours: string, minutes: string, seconds: string, milliseconds: string): number {
    return parseInt(hours) * 3600 + 
           parseInt(minutes) * 60 + 
           parseInt(seconds) + 
           parseInt(milliseconds) / 1000;
  }

  /**
   * Select the best subtitle track based on preferences
   */
  private selectBestTrack(
    tracks: SubtitleTrack[], 
    preferredLanguage: string, 
    preferAutoGenerated: boolean
  ): SubtitleTrack | null {
    // First, try to find exact match with preference
    let bestTrack = tracks.find(t => 
      t.languageCode === preferredLanguage && 
      t.isAutoGenerated === preferAutoGenerated
    );

    if (bestTrack) return bestTrack;

    // Try to find language match regardless of auto-generated status
    bestTrack = tracks.find(t => t.languageCode === preferredLanguage);
    if (bestTrack) return bestTrack;

    // Try to find language variant (e.g., 'en-US' when looking for 'en')
    bestTrack = tracks.find(t => t.languageCode.startsWith(preferredLanguage));
    if (bestTrack) return bestTrack;

    return null;
  }

  /**
   * Get language name from code
   */
  private getLanguageName(code: string): string {
    const languageNames: { [key: string]: string } = {
      'en': 'English',
      'en-US': 'English (US)',
      'en-GB': 'English (UK)',
      'es': 'Spanish',
      'es-ES': 'Spanish (Spain)',
      'es-MX': 'Spanish (Mexico)',
      'fr': 'French',
      'de': 'German',
      'it': 'Italian',
      'pt': 'Portuguese',
      'pt-BR': 'Portuguese (Brazil)',
      'ru': 'Russian',
      'ja': 'Japanese',
      'ko': 'Korean',
      'zh': 'Chinese',
      'zh-CN': 'Chinese (Simplified)',
      'zh-TW': 'Chinese (Traditional)',
      'ar': 'Arabic',
      'hi': 'Hindi',
      'tr': 'Turkish',
      'pl': 'Polish',
      'nl': 'Dutch',
      'sv': 'Swedish',
      'da': 'Danish',
      'no': 'Norwegian',
      'fi': 'Finnish'
    };

    return languageNames[code] || code;
  }

  /**
   * Create overlapping chunks for AI processing
   */
  public createOverlappingChunks(
    segments: TranscriptSegment[], 
    chunkDuration: number = 30, // seconds
    overlapDuration: number = 5 // seconds
  ): TranscriptSegment[][] {
    const chunks: TranscriptSegment[][] = [];
    let currentChunk: TranscriptSegment[] = [];
    let chunkStartTime = 0;

    for (let i = 0; i < segments.length; i++) {
      const segment = segments[i];
      
      // Add segment to current chunk
      currentChunk.push(segment);

      // Check if we should start a new chunk
      if (segment.endTime - chunkStartTime >= chunkDuration) {
        chunks.push([...currentChunk]);

        // Find overlap start point
        let overlapStartIndex = currentChunk.length - 1;
        while (overlapStartIndex > 0 && 
               segment.endTime - currentChunk[overlapStartIndex].startTime < overlapDuration) {
          overlapStartIndex--;
        }

        // Start new chunk with overlap
        currentChunk = currentChunk.slice(overlapStartIndex);
        chunkStartTime = currentChunk[0].startTime;
      }
    }

    // Add remaining segments as final chunk
    if (currentChunk.length > 0) {
      chunks.push(currentChunk);
    }

    return chunks;
  }
}